apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: md-postgres
data:
  init.sql: |
    CREATE DATABASE mddb_catalog;
    CREATE DATABASE mddb_order;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-postgres
  labels:
    db: md-postgres
spec:
  selector:
    matchLabels:
      db: md-postgres
  template:
    metadata:
      labels:
        db: md-postgres
    spec:
      containers:
        - name: md-postgres
          image: postgres:14.4
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: '1234567890'
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: md-postgres
  labels:
    db: md-postgres
spec:
  type: ClusterIP
  selector:
    db: md-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
