version: "3.8"
services:
  catalog-service:
    depends_on:
      - md-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://md-postgres:5432/mddb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  order-service:
    depends_on:
      - md-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://md-postgres:5432/mddb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://md-postgres:5432/mddb_order

  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  md-postgres:
    image: "postgres:14.4"
    container_name: "md-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  md-redis:
    image: "redis:7.0"
    container_name: "md-redis"
    ports:
      - 6379:6379